// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCep9zMga8b8IbDO6LX3iz6ChAuDE39IiI',
    appId: '1:438974303719:web:dc014d04e99701d5794142',
    messagingSenderId: '438974303719',
    projectId: 'flutter-firebase-b1746',
    authDomain: 'flutter-firebase-b1746.firebaseapp.com',
    storageBucket: 'flutter-firebase-b1746.appspot.com',
    measurementId: 'G-L5N2VZ1PER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfC5fmDKefXVLWKoLX0tcwbQWbxgzjDww',
    appId: '1:438974303719:android:0f98b0a42ecb7551794142',
    messagingSenderId: '438974303719',
    projectId: 'flutter-firebase-b1746',
    storageBucket: 'flutter-firebase-b1746.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADXaXyD5w7iKT5aXyPUuw8QBvC_lEJbpo',
    appId: '1:438974303719:ios:16e5e58bb9717188794142',
    messagingSenderId: '438974303719',
    projectId: 'flutter-firebase-b1746',
    storageBucket: 'flutter-firebase-b1746.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADXaXyD5w7iKT5aXyPUuw8QBvC_lEJbpo',
    appId: '1:438974303719:ios:db01d96190112181794142',
    messagingSenderId: '438974303719',
    projectId: 'flutter-firebase-b1746',
    storageBucket: 'flutter-firebase-b1746.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
